model_list:
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini-2.0-flash-lite
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-1.5-pro
    litellm_params:
      model: gemini-1.5-pro
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-1.5-flash
    litellm_params:
      model: gemini-1.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: xxxxx  # Master key for proxy admin - must start with 'sk-'
  database_url: "postgresql://postgres:123456@database:5432/litellm"
